# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_7tg4ljXBuLNCB-GU063S4LsNUoSAlZ
"""

print("Hello, World!hi")

